<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>DeBR</title>
	<!-- CSS only -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<!-- JavaScript Bundle with Popper -->
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="theme-color" content="#7952b3"><meta name="msapplication-TileColor" content="#ffffff">
    <link href="/CSS/styleFonte.css" rel="stylesheet">
    <script defer src="/JS/funcoes.js"></script>
</head>
<body>


<!-- Modal -->
<!-- Modal -->
<div class="modal fade " id="Modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document" style='border: dashed; border-color: green'>
    <div class="modal-content" style='background-color: black'>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel" style='color: rgba(4, 143, 14, 0.8); text-align: center'> Veja o enigma abaixo</h5>
        
      </div>

      <div class="modal-body">
        <img src="img/arte_do_instagram.png" class="img-fluid" alt="Responsive image">
		
		
		
      </div>

      <div class="modal-footer">
        <button type="button" id='btnResposta' class="btn btn-primary" style='background-color: rgba(4, 143, 14, 0.8); border-color: black' onclick='Pergunta1()' >Responder Enigma</button>
      </div>
      
    </div>
  </div>
</div>
							
    <div class='container-fluid' style='height: 100vh; position: absolute'>
        <div class='row'>
            <div id='conteudo'  class='col-sm-12' style='color: rgba(4, 143, 14, 0.8); font-size: 20px;'>
                <img class='img-responsive' src="img/logo.png" width='300px'>

                <p>[Versão 2022] Todos os direitos reservados.</p>
                <br>
                <p  id='txt1' name='paragrafos' style='display: block' class='line piscar' data-texto='txt1'></p>
                <p  id='txt2' name='paragrafos' style='display: none' data-texto='txt2'></p>
                <p  id='txt3' name='paragrafos' style='display: none' data-texto='txt3'></p>

            </div>
        </div> 


        <div class='row'>
            <div   class='col-sm-6 ' style=' color: rgba(4, 143, 14, 0.8); font-size: 20px;'>
            <br>
                <div class="form-group row" id='formulario'>
                              
                </div>
            </div>
            
        </div>

        <div class='row'>
            <div  class='col-sm-6 ' style=' color: rgba(4, 143, 14, 0.8); font-size: 20px;'>
                <br>
                <div class="form-group row">
                    <button id="btnEnviar" name="btnEnviar" style="background: black; outline: 0px; color: green; border: dashed; width: 500px; display: none;" type="text">Enviar</button>
                </div>
                <br>
            </div>
        </div>
   
        
       
    </div>

    <footer class="footer navbar-fixed-bottom" style='position: fixed; bottom: 0; right: 0'>
       
                <img style='float: right; opacity: 30%;' src="img/logo2.png" width='100px'>
           
       
    </footer>


    

</body>
</html>